AWSTemplateFormatVersion: '2010-09-09'
Description: 'Obsidian vault S3 bucket with CORS and IAM user'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Suspended
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - x-amz-meta-mtime

  IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub '${AWS::StackName}-s3-user'
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                  - 's3:DeleteObject'
                Resource:
                  - !GetAtt S3Bucket.Arn
                  - !Sub '${S3Bucket.Arn}/*'

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket

  IAMUser:
    Description: IAM user
    Value: !Ref IAMUser